import type { Metadata } from "next";
import { Roboto, Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

// Roboto
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

// Inter
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${inter.variable} antialiased min-h-screen bg-gradient-to-br from-[#1E1B4B] via-[#581C87] to-[#1E1B4B]`}
      >
        {children}
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
